export const PRODUCTS_GET_ALL = 'PRODUCTS_GET_ALL';
export const PRODUCTS_GET_REJECTED = 'PRODUCTS_GET_REJECTED';
export const PRODUCTS_GET_FULFILLED = 'PRODUCTS_GET_FULFILLED';
export const PRODUCTS_CREATE_NEW = 'PRODUCTS_CREATE_NEW';
export const PRODUCTS_EDIT_EXISTING = 'PRODUCTS_EDIT_EXISTING';
export const PRODUCTS_TRANSACTIONS_TOGGLE = 'PRODUCTS_TRANSACTIONS_TOGGLE';
export const PRODUCTS_SAVE_NEW_FULFILLED = 'PRODUCTS_SAVE_NEW_FULFILLED';
export const PRODUCTS_SAVE_UPDATE_FULFILLED = 'PRODUCTS_SAVE_UPDATE_FULFILLED';
export const PRODUCTS_SAVE_REJECTED = 'PRODUCTS_SAVE_REJECTED';

